notify 200 {
    match "system"          "CARP";
    match "type"            "MASTER";
    action "/usr/local/sbin/pfSctl -c 'interface carpmaster '$subsystem; /usr/sbin/daemon -f /usr/local/sbin/pppoe_toggle_ha $subsystem $type";
};

notify 200 {
    match "system"          "CARP";
    match "type"            "BACKUP";
    action "/usr/local/sbin/pfSctl -c 'interface carpbackup '$subsystem; /usr/sbin/daemon -f /usr/local/sbin/pppoe_toggle_ha $subsystem $type";
};

notify 200 {
    match "system"          "CARP";
    match "type"            "INIT";
    action "/usr/local/sbin/pfSctl -c 'interface carpbackup '$subsystem; /usr/sbin/daemon -f /usr/local/sbin/pppoe_toggle_ha $subsystem $type";
};
